# .github/workflows/merge-upstream.yml

name: Merge Upstream freqstart Repository
on:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '0 0,4,8,12,16,20 * * *'
  workflow_dispatch:
jobs:
  Merge-freqstart:
    environment: default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge Upstream freqstart
        env:
          GHUSER: ${{ secrets.GHUSER }}
          GHEMAIL: ${{ secrets.GHEMAIL }}
        run: ./.github/workflows/scripts/merge.sh
